# Generated by Django 4.1.7 on 2023-03-09 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_alter_post_category_categoryuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscr', through='news.CategoryUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
